# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('corecluster', '0039_agent_authorized_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='execution_time',
            field=models.DurationField(help_text=b'Total time spent on function execution. Divided by requests equals to average time', default=datetime.timedelta()),
        ),
    ]