# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecluster', '0040_timedelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='vnc_address',
            field=models.CharField(default=b'', max_length=128, null=True),
        ),
    ]