# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecluster', '0041_vm_vnc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='networkpool',
            name='address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='networkpool',
            name='mask',
            field=models.PositiveIntegerField(help_text=b'Network mask in short format (e.g. 24 for 255.255.255.0 network)'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='mask',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='v_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text=b'VLAN or VxLAN id. Used only with isolated network pools', null=True),
        ),
    ]