# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecluster', '0042_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='address',
            field=models.GenericIPAddressField(help_text=b'Node ip address'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]