# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecluster', '0043_ipv6_infra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='hostname',
            field=models.CharField(default=b'vm', max_length=200),
        ),
    ]
